import "./globals.css"
import { Inter } from "next/font/google"
import Header from "./header"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "پیاده سازی الگوریتم سلام",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="dark" lang="en">
      <body
        className={`${inter.className} dark:bg-stone-800 dark:text-gray-100`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
